# Generated by Django 6.0.7 on 2026-07-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmnails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
